apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    createNamespace: true # Ensures the namespace is created if it doesn’t exist
    remediation:
      retries: 3
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: ">1.17.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    crds:
      enable: true
    prometheus:
      enable: false
