apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  releaseName: haproxy-ingress
  targetNamespace: haproxy-ingress
  install:
    createNamespace: true # Ensures the namespace is created if it doesn’t exist
    remediation:
      retries: 3
  interval: 10m
  chart:
    spec:
      chart: haproxy-ingress
      version: ">0.14.0"
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
  values:
    controller:
      hostNetwork: true
      ingressClassResource:
        enabled: true
      daemonset:
        
      service:
        httpPort:
          enabled: true
          - port: 81
          - targetPort: http
        httpsPort:
          enabled: true
          - port: 7443
          - targetPort: https
        enabled: true
        type: LoadBalancer
        externalIPs:
        - 10.10.10.11
        - 10.10.10.12