apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  targetNamespace: cilium
  install:
    createNamespace: true # Ensures the namespace is created if it doesn’t exist
    remediation:
      retries: 3
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: ">1.17.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    nodePort:
      enabled: true
    kubeProxyReplacement: true
    ingressController:
       enabled: true
       default: true
       service:
         externalTrafficPolicy: Cluster
         type: LoadBalancer
       loadbalancerMode: dedicated
    l2announcements:
       enabled: true
    gatewayAPI:
      enabled: true
      enaableAlpn: true
      enableAppProtocols: true
    bgpconntrolPlane:
      enabled: true
    externalIPs:
      enabled: true
    k8sServiceHost: 10.10.10.10
    k8sServicePort: 6443
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true 